name: Build V8

on:
  push:
    branches:
      - "test"
    paths:
    - 'V8_VERSION'
    - 'builders/**'
    - '.github/workflows/build.yml'
  pull_request:
    branches:
      - "test"

jobs:

  version_reader:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      v8_version: ${{ steps.got_version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: got_version
      run: |
        cd $GITHUB_WORKSPACE
        echo "::set-output name=version::$(<./V8_VERSION)"

  build_android_arm_v8:
    name: Android (arm64-v8a)
    runs-on: ubuntu-20.04
    needs: version_reader
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./builders/v8-android-arm-v8.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: android_arm64-v8a
        path: |
          ~/v8/v8/out.gn/arm64.release/obj/*.a
          ~/v8/v8/out.gn/arm64.release/*.so

  headers_and_documentation:
    name: Headers and Documentation
    runs-on: ubuntu-20.04
    needs: version_reader
    steps:
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        cd $GITHUB_WORKSPACE
        sh ./builders/v8-docs.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: headers
        path: '~/v8/v8/include'
    - uses: actions/upload-artifact@v2
      with:
        name: license
        path: '~/v8/v8/LICENSE.v8'

  release:
    name: Release
    if: >-
      startsWith(github.event.head_commit.message, '[Release]') &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [
      version_reader,
      build_android_arm_v8, build_android_arm_v7, build_android_x86_64, build_android_x86,
      headers_and_documentation
    ]
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: 'v8'
    - name: Make zip
      run: |
        zip -r v8_engine.zip v8
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version_reader.outputs.v8_version }}
        release_name: V8 engine, version ${{ needs.version_reader.outputs.v8_version }}
        draft: true
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: v8_engine.zip
        asset_name: v8_engine_${{ needs.version_reader.outputs.v8_version }}.zip
        asset_content_type: application/zip
