name: Build V8

on:
  push:
    branches:
      - "test"
    paths:
    - 'V8_VERSION'
    - 'builders/**'
    - '.github/workflows/build.yml'
  pull_request:
    branches:
      - "test"

jobs:

  version_reader:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      v8_version: ${{ steps.got_version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: got_version
      run: |
        cd $GITHUB_WORKSPACE
        echo "::set-output name=version::$(<./V8_VERSION)"

  build_android_arm_v8:
    name: Android (arm64-v8a)
    runs-on: ubuntu-20.04
    needs: version_reader
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./builders/v8-android-arm-v8.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: android_arm64-v8a
        path: |
          ~/v8/v8/out.gn/arm64.release/obj/*.a
          ~/v8/v8/out.gn/arm64.release/*.so

  headers_and_documentation:
    name: Headers and Documentation
    runs-on: ubuntu-20.04
    needs: version_reader
    steps:
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        cd $GITHUB_WORKSPACE
        sh ./builders/v8-docs.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: headers
        path: '~/v8/v8/include'
    - uses: actions/upload-artifact@v2
      with:
        name: license
        path: '~/v8/v8/LICENSE.v8'
