name: Build V8

on:
  push:
    branches:
      - "test"
    paths:
    - 'V8_VERSION'
    - 'builders/**'
    - '.github/workflows/build.yml'
  pull_request:
    branches:
      - "test"

jobs:

  version_reader:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      v8_version: ${{ steps.got_version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: got_version
      run: |
        cd $GITHUB_WORKSPACE
        echo "::set-output name=version::$(<./V8_VERSION)"

  build_android_arm_v7:
    name: Android (armeabi-v7a)
    runs-on: ubuntu-20.04
    needs: version_reader
    steps:
    - uses: actions/checkout@v2
    - name: fix libatomic.so.1
      run: |
        sudo apt install libatomic1
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./builders/v8-android-arm-v7.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v2
      with:
        name: android_armeabi-v7a
        path: |
          ~/v8/v8/out.gn/arm.release/obj/*.a
          ~/v8/v8/out.gn/arm.release/*.so

